apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-config
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
  RABBITMQ_ERLANG_COOKIE: stratus
  RABBITMQ_NODENAME: rabbit@rabbit-0
