apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
spec:
  serviceName: rabbit
  selector:
    matchLabels:
      role: rabbit
  template:
    metadata:
      labels:
        role: rabbit
        type: backend
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: 'true'
    spec:
      nodeSelector:
        backend: 'true'
      containers:
        - name: rabbit
          image: rabbitmq:3.6-management-alpine
          envFrom:
            - secretRef:
                name: rabbit-secret
          ports:
            - name: queue
              containerPort: 5672
              hostPort: 5672
            - name: management
              containerPort: 15672
              hostPort: 15672
            - name: cluster
              containerPort: 4369
              hostPort: 4369
            - name: dist
              containerPort: 25672
              hostPort: 25672
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - rabbitmqctl
                - status
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
          volumeMounts:
            - name: volume
              mountPath: /var/lib/rabbitmq:rw
      volumes:
        - name: volume
          emptyDir:
