apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    role: rabbit
spec:
  clusterIP: None
  ports:
    - port: 5672
      name: amqp
    - port: 4369
      name: epmd
    - port: 25672
      name: dist
  selector:
    role: rabbit
