apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couch
spec:
  serviceName: couch
  selector:
    matchLabels:
      role: couch
  template:
    metadata:
      labels:
        role: couch
    spec:
      nodeSelector:
        backend: 'true'
      containers:
        - name: couch
          image: couchdb:1.7
          ports:
            - containerPort: 5984
              name: http
          volumeMounts:
            - name: storage
              subPath: data
              mountPath: /opt/couchdb/data:rw
            - name: storage
              subPath: config
              mountPath: /opt/couchdb/etc:rw
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
