apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couch
spec:
  serviceName: couch
  selector:
    matchLabels:
      role: couch
  template:
    metadata:
      labels:
        role: couch
        type: backend
    spec:
      nodeSelector:
        backend: 'true'
      containers:
        - name: couch
          image: couchdb:1.7
          ports:
            - containerPort: 5984
              name: http
          volumeMounts:
            - name: volume
              subPath: data
              mountPath: /opt/couchdb/data:rw
            - name: volume
              subPath: config
              mountPath: /opt/couchdb/etc:rw
          resources:
            requests:
              cpu: 50m
              memory: 25Mi
      volumes:
        # Manual setup for a mounted EXT4 block storage device
        - name: volume
          hostPath:
            path: /mnt/couch
