apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  KUBERNETES_MONGO_SERVICE_NAME: mongo
  MONGO_SIDECAR_POD_LABELS: role=mongo
  MONGO_SIDECAR_UNHEALTHY_SECONDS: '86400'
  MONGO_SIDECAR_SLEEP_SECONDS: '5'
  MONGODB_DATABASE: admin
