apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      role: proxy
  template:
    metadata:
      labels:
        role: proxy
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        bungee: 'true'
      containers:
        - name: proxy
          image: gcr.io/stratus-181519/proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              hostPort: 25565
              name: minecraft
          env:
            - name: PROXY_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: PROXY_EXTERNAL_PORT
              value: '25565'
            - name: PROXY_INTERNAL_PORT
              value: '32223'
            - name: PROXY_INTERNAL_PORT_SECONDARY
              value: '32223'
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
