apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      role: proxy
  template:
    metadata:
      labels:
        role: proxy
        type: minecraft
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        bungee: 'true'
      containers:
        - name: proxy
          image: gcr.io/stratus-197318/proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              hostPort: 25565
              name: proxy
            - containerPort: 25568
              hostPort: 25568
              name: passthrough
          env:
            - name: INTERNAL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: PROXY_PORT
              value: '25565'
            - name: PASSTHROUGH_PORT
              value: '25568'
            - name: INTERNAL_PORT
              value: '25566'
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
