apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bungee-patch
spec:
  schedule: '0 10 * * *' # 2am pst
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: bungee-patch
    spec:
      template:
        metadata:
          labels:
            role: bungee-patch
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          nodeSelector:
            node-role.kubernetes.io/master: ''
          containers:
            - name: bungee-patch
              image: stratusnetwork/kubectl:latest
              args:
                - delete
                - pods
                - -l
                - role=bungee
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
          volumes:
            - name: kube
              hostPath:
                path: /root/.kube
