apiVersion: v1
kind: Service
metadata:
  name: bungee
  labels:
    role: bungee
spec:
  type: NodePort
  externalTrafficPolicy: Local
  clusterIP: 10.96.0.50
  ports:
    - targetPort: 25565
      port: 25566
      nodePort: 25566
      name: minecraft
  selector:
    role: bungee
