apiVersion: v1
kind: Service
metadata:
  name: bungee
  labels:
    role: bungee
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  clusterIP: 10.96.0.50
  ports:
    - port: 32223
      nodePort: 32223
      name: minecraft
  selector:
    role: bungee
