apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bungee
spec:
  serviceName: bungee
  replicas: 2
  selector:
    matchLabels:
      role: bungee
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: bungee
        type: minecraft
    spec:
      nodeSelector:
        bungee: 'true'
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    role: bungee
      containers:
        - name: bungee
          image: gcr.io/stratus-197318/minecraft:bungee-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - ready?
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - alive?
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 25565
          ports:
            - containerPort: 25565
              name: minecraft
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
          envFrom:
            - secretRef:
                name: minecraft-secret
          env:
            - name: REPLICA
              value: enabled
