apiVersion: v1
kind: Service
metadata:
  name: official
  namespace: tm
  labels:
    role: official
spec:
  clusterIP: None
  ports:
    - port: 25565
      name: minecraft
  selector:
    role: official
