apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: lobby
  namespace: tm
spec:
  serviceName: lobby
  replicas: 1
  template:
    metadata:
      labels:
        role: lobby
    spec:
      containers:
        - name: lobby
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
              name: mc
          envFrom:
            - configMapRef:
                name: lobby-config
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
      volumes:
        - name: maps
          hostPath:
            path: maps
