apiVersion: v1
kind: ConfigMap
metadata:
  name: spaces-config
  namespace: kube-system
data:
  BUCKET_NAME: stratus
  BUCKET_LOCATION: US
  BUCKET_REGION: nyc3
  BUCKET_ACL: private
  BUCKET_ACL_SELECTOR: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spaces-web-config
  namespace: kube-system
data:
  BUCKET_FOLDER: web
  BUCKET_ACL: public
  BUCKET_GIT: https://github.com/StratusNetwork/OCN.git
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spaces-maps-config
  namespace: kube-system
data:
  BUCKET_FOLDER: maps
  BUCKET_ACL: public
  BUCKET_ACL_SELECTOR: xml,png
