apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: web
spec:
  schedule: '0 8 * * *' # midnight pst
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: web  
    spec:
      template:
        metadata:
          labels:
            role: web
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          #nodeSelector:
          #  node-role.kubernetes.io/master: ''
          containers:
            - name: web
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - deployment
                - web
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
          volumes:
            - name: kube
              hostPath:
                path: /root/.kube
