apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: web
spec:
  schedule: '0 10 * * *' # 2am pst
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: web
    spec:
      template:
        metadata:
          labels:
            role: web
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          serviceAccountName: system
          containers:
            - name: api
              image: lachlanevenson/k8s-kubectl:latest
              args:
                - patch
                - deployment
                - web
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
