apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sorx4s
spec:
  serviceName: sorx4s
  selector:
    matchLabels:
      role: private
      user: sorx4s
  template:
    metadata:
      labels:
        role: private
        user: sorx4s
        type: minecraft
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: minecraft
          image: gcr.io/stratus-197318/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - ready?
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - alive?
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 2000m
              memory: 1Gi
          envFrom:
            - secretRef:
                name: minecraft-secret
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps-private
