steps:
  - id: worker
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/worker:latest
      - --file=models/worker/Dockerfile
      - .
images:
  - gcr.io/$PROJECT_ID/worker:latest
