custom_server_name: BungeeCord
log_commands: false
listeners:
- query_port: $SERVER_PORT
  motd: |-
    Stratus Network - Internal Error
  priorities:
  - default
  bind_local_address: true
  tab_list: SERVER
  query_enabled: false
  host: 0.0.0.0:$SERVER_PORT
  forced_hosts: {}
  max_players: 1
  tab_size: 60
  ping_passthrough: true
  force_default_server: false
  proxy_protocol: $SERVER_PROXY
name: Connect with
online_mode: true
connection_throttle: -1
ip_forward: true
always_handle_packets: false
network_compression_threshold: 256
stats: 382055f7-b196-48db-b636-a97aea12b388
require_all_plugins: true
disabled_commands:
- disabledcommandhere
prevent_proxy_connections: false
timeout: 30000
servers:
  default:
    motd: Lobby
    address: $SERVER_LOBBY_IP:$SERVER_LOBBY_PORT
    restricted: false
player_limit: -1