steps:
  - id: git
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=git
      - --tag=gcr.io/$PROJECT_ID/git:latest
      - docker/other/git
  - id: maven
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/maven:latest
      - docker/other/maven
    wait_for:
      - '-'
  - id: gradle
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/gradle:latest
      - docker/other/gradle
    wait_for:
      - '-'
  - id: kubectl
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/kubectl:latest
      - docker/other/kubectl
    wait_for:
      - '-'
  - id: spaces
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/spaces:latest
      - docker/other/spaces
    wait_for:
      - git
  - id: proxy
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/proxy:latest
      - docker/other/proxy
    wait_for:
      - '-'
  - id: request
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/minecraft:request
      - docker/other/request
    wait_for:
      - '-'
images:
  - gcr.io/$PROJECT_ID/git:latest
  - gcr.io/$PROJECT_ID/maven:latest
  - gcr.io/$PROJECT_ID/gradle:latest
  - gcr.io/$PROJECT_ID/kubectl:latest
  - gcr.io/$PROJECT_ID/spaces:latest
  - gcr.io/$PROJECT_ID/proxy:latest
  - gcr.io/$PROJECT_ID/minecraft:request
