apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps
spec:
  minReadySeconds: 30
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: maps
  template:
    metadata:
      labels:
        role: maps
    spec:
      nodeSelector:
        web: 'true'
      containers:
        - name: maps
          image: stratusnetwork/redirect
          ports:
            - containerPort: 80
              name: maps
          env:
            - name: REDIRECT_TARGET
              value: https://stratus.nyc3.digitaloceanspaces.com
          resources:
            requests:
              memory: 5Mi
              cpu: 5m
