apiVersion: v1
kind: ConfigMap
metadata:
  name: spaces-config
data:
  BUCKET_NAME: stratus
  BUCKET_LOCATION: US
  BUCKET_REGION: nyc3
  BUCKET_ACL: private
  BUCKET_ACL_SELECTOR: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spaces-maps-config
data:
  BUCKET_FOLDER: maps
  BUCKET_ACL: public
  BUCKET_ACL_SELECTOR: xml,png
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spaces
spec:
  template:
    metadata:
      labels:
        role: spaces
    spec:
      containers:
        - name: maps
          image: stratusnetwork/spaces
          envFrom:
            - secretRef:
                name: spaces-secret
            - secretRef:
                name: maps-secret
            - configMapRef:
                name: spaces-config
            - configMapRef:
                name: spaces-maps-config
          volumeMounts:
            - name: git
              subPath: maps-master
              mountPath: /data
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: git
