steps:
  - id: git
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - --depth=1
      - https://github.com/Electroid/infrastructure.git
  - id: base
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:base
      - --file=infrastructure/models/minecraft/Dockerfile
      - --build-arg=PROJECT_ID=$PROJECT_ID
      - --build-arg=BRANCH=$_BRANCH
      - --build-arg=VERSION=$_VERSION
      - infrastructure
    wait_for:
      - git
  - id: bukkit
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/minecraft:bukkit-$_BRANCH
      - --file=infrastructure/models/minecraft/Dockerfile-bukkit
      - --build-arg=BUKKIT_VERSION=$BUKKIT_VERSION
      - infrastructure
    wait_for:
      - base
  - id: bungee
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/minecraft:bungee-$_BRANCH
      - --file=infrastructure/models/minecraft/Dockerfile-bungee
      - --build-arg=BUNGEE_VERSION=$BUNGEE_VERSION
      - infrastructure
    wait_for:
      - base
images:
  - gcr.io/$PROJECT_ID/minecraft:bukkit-$_BRANCH
  - gcr.io/$PROJECT_ID/minecraft:bungee-$_BRANCH
