apiVersion: v1
kind: Service
metadata:
  name: mapdev
  labels:
    role: mapdev
spec:
  clusterIP: 10.96.0.68
  ports:
    - port: 25565
      name: minecraft
    - port: 25555
      name: request
  selector:
    role: mapdev
