apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapdev
spec:
  serviceName: mapdev
  selector:
    matchLabels:
      role: mapdev
  template:
    metadata:
      labels:
        role: mapdev
        type: minecraft
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: minecraft
          image: gcr.io/stratus-197318/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - ready?
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - alive?
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
          envFrom:
            - secretRef:
                name: minecraft-secret
          volumeMounts:
            - name: dropbox
              mountPath: /minecraft/maps:rw
        - name: dropbox
          image: gcr.io/stratus-197318/dropbox:master
          envFrom:
            - secretRef:
                name: dropbox-secret
          env:
            - name: DROPBOX_FOLDER_REMOTE
              value: /mapdev
          resources:
            requests:
              cpu: 50m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          volumeMounts:
            - name: dropbox
              mountPath: /dropbox:rw
      volumes:
        - name: dropbox
          hostPath:
            path: /storage/dropbox/mapdev
