apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: storage
  namespace: tm
spec:
  template:
    metadata:
      labels:
        role: storage
    spec:
      containers:
        - name: maps
          image: stratusnetwork/git
          envFrom:
            - secretRef:
                name: maps-secret
          env:
            - name: GIT_BRANCH
              value: tournament
          volumeMounts:
            - name: maps
              mountPath: /data
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps-tournament
