steps:
  - id: clone
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - --depth=1
      - https://github.com/StratusNetwork/docker.git
  - id: bukkit-base
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:bukkit-base
      - --file=docker/minecraft/bukkit/Dockerfile-base
      - --build-arg=PROJECT_ID=$PROJECT_ID
      - --build-arg=BRANCH=$_BRANCH
      - --build-arg=VERSION=$_VERSION
      - --build-arg=SPORTBUKKIT_VERSION=$_SPORTBUKKIT_VERSION
      - docker/minecraft/bukkit
    wait_for:
      - clone
  - id: bukkit-shared
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:bukkit-shared
      - --build-arg=BASE=bukkit
      - docker/minecraft/shared
    wait_for:
      - bukkit-base 
  - id: bukkit
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:bukkit
      - --tag=gcr.io/$PROJECT_ID/minecraft:bukkit-$_BRANCH
      - docker/minecraft/bukkit
    wait_for:
      - bukkit-shared
  - id: bungee-base
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:bungee-base
      - --file=docker/minecraft/bungee/Dockerfile-base
      - --build-arg=PROJECT_ID=$PROJECT_ID
      - --build-arg=BRANCH=$_BRANCH
      - --build-arg=VERSION=$_VERSION
      - --build-arg=BUNGEECORD_VERSION=$_BUNGEECORD_VERSION
      - docker/minecraft/bungee
    wait_for:
      - clone
  - id: bungee-shared
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:bungee-shared
      - --build-arg=BASE=bungee
      - docker/minecraft/shared
    wait_for:
      - bungee-base
  - id: bungee
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=minecraft:bungee
      - --tag=gcr.io/$PROJECT_ID/minecraft:bungee-$_BRANCH
      - docker/minecraft/bungee
    wait_for:
      - bungee-shared
images:
  - gcr.io/$PROJECT_ID/minecraft:bukkit-$_BRANCH
  - gcr.io/$PROJECT_ID/minecraft:bungee-$_BRANCH
