apiVersion: v1
kind: Service
metadata:
  name: alpha
  labels:
    role: alpha
spec:
  clusterIP: 10.96.0.69
  ports:
    - port: 25565
      name: minecraft
    - port: 25555
      name: request
  selector:
    role: alpha
