boundaries:
  use-world-border: false
  min:
  - -100
  - -100
  - -100
  max:
  - 100
  - 200
  - 100
exempt: []
disabled-permissions: []
portals:
  portals:
    Beta:
      min:
      - -22.0
      - 5.0
      - -1.0
      max:
      - -21.0
      - 9.0
      - 2.0
      to: '@Beta'
  enabled: true
