apiVersion: v1
kind: Service
metadata:
  name: lobby
  namespace: tm
  labels:
    role: lobby
spec:
  clusterIP: 10.96.0.59
  ports:
    - port: 25565
      name: minecraft
  selector:
    role: lobby
