apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: lobby
  namespace: tm
spec:
  serviceName: lobby
  replicas: 3
  selector:
    matchLabels:
      role: lobby
  template:
    metadata:
      labels:
        role: lobby
    spec:
      nodeSelector:
        # lobby: 'true'
        tm: 'true'
      containers:
        - name: lobby
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 1337
              name: mc
          envFrom:
            - configMapRef:
                name: lobby-config
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 5Gi
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
            - name: config
              mountPath: /minecraft/repo/Config:ro
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps-tournament
        - name: config
          hostPath:
            path: /storage/Config
