apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  minReadySeconds: 30
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: shop
  template:
    metadata:
      labels:
        role: shop
    spec:
      nodeSelector:
        web: 'true'
      containers:
        - name: shop
          image: stratusnetwork/redirect
          ports:
            - containerPort: 80
              name: shop
          env:
            - name: REDIRECT_TARGET
              value: https://stratusnetwork.buycraft.net
          resources:
            requests:
              memory: 5Mi
              cpu: 5m
