apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lobby
spec:
  schedule: '0 12 * * *' # 4am pst
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: lobby
    spec:
      template:
        metadata:
          labels:
            role: lobby
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          serviceAccountName: system
          containers:
            - name: kubectl
              image: lachlanevenson/k8s-kubectl:latest
              args:
                - delete
                - pod
                - lobby-us-0
