apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lobby
spec:
  schedule: '0 8 * * *' # midnight pst
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: lobby  
    spec:
      template:
        metadata:
          labels:
            role: lobby
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          nodeSelector:
            node-role.kubernetes.io/master: ''
          containers:
            - name: lobby
              image: stratusnetwork/kubectl:latest
              args:
                - delete
                - pod
                - lobby-us-0
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
          volumes:
            - name: kube
              hostPath:
                path: /root/.kube
