apiVersion: v1
kind: Service
metadata:
  name: lobby
  labels:
    role: lobby
spec:
  # Give Lobby dedicated IP so restarts don't cause
  # DNS issues where the cached IP is served.
  clusterIP: 10.96.0.69
  ports:
    - port: 25565
      name: minecraft
  selector:
    role: lobby
