apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby
spec:
  serviceName: lobby
  selector:
    matchLabels:
      role: lobby
  template:
    metadata:
      labels:
        role: lobby
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: minecraft
          image: gcr.io/stratus-197318/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - ready?
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - alive?
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1500m
              memory: 2Gi
          envFrom:
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps
