apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby
spec:
  serviceName: lobby
  replicas: 1
  selector:
    matchLabels:
      role: lobby
  template:
    metadata:
      labels:
        role: lobby
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: lobby
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            exec:
              command:
                - ./health.sh
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            exec:
              command:
                - ./health.sh
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
<<<<<<< Updated upstream
              cpu: 1500m
=======
              cpu: 2000m
>>>>>>> Stashed changes
              memory: 2Gi
          envFrom:
            - configMapRef:
                name: lobby-config
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
            - name: config
              mountPath: /minecraft/repo/Config:ro
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps
        - name: config
          hostPath:
            path: /storage/Config
