steps:
  - id: git
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=git
      - --tag=gcr.io/$PROJECT_ID/git:latest
      - models/util/git
  - id: spaces
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/spaces:latest
      - models/util/spaces
    wait_for:
      - git
  - id: proxy
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/proxy:latest
      - models/util/proxy
    wait_for:
      - '-'
images:
  - gcr.io/$PROJECT_ID/git:latest
  - gcr.io/$PROJECT_ID/spaces:latest
  - gcr.io/$PROJECT_ID/proxy:latest
