steps:
  - id: git
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=git
      - --tag=gcr.io/$PROJECT_ID/git:latest
      - models/util/git
  - id: maven
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/maven:latest
      - models/util/maven
    wait_for:
      - '-'
  - id: gradle
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/gradle:latest
      - models/util/gradle
    wait_for:
      - '-'
  - id: kubectl
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/kubectl:latest
      - models/util/kubectl
    wait_for:
      - '-'
  - id: spaces
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/spaces:latest
      - models/util/spaces
    wait_for:
      - git
  - id: proxy
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/proxy:latest
      - models/util/proxy
    wait_for:
      - '-'
images:
  - gcr.io/$PROJECT_ID/git:latest
  - gcr.io/$PROJECT_ID/maven:latest
  - gcr.io/$PROJECT_ID/gradle:latest
  - gcr.io/$PROJECT_ID/kubectl:latest
  - gcr.io/$PROJECT_ID/spaces:latest
  - gcr.io/$PROJECT_ID/proxy:latest
