steps:
  - id: default-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/default-backend:latest
      - --file=models/default-backend/Dockerfile
      - .
images:
  - gcr.io/$PROJECT_ID/default-backend:latest
