apiVersion: v1
kind: Service
metadata:
  name: hillbillyhero
  labels:
    user: hillbillyhero
spec:
  clusterIP: None
  ports:
    - port: 25565
      name: minecraft
  selector:
    user: hillbillyhero
