apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: tm
  labels:
    role: bungee
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25570
      name: mc
  selector:
    role: bungee
