apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: bungee
  namespace: tm
spec:
  serviceName: bungee
  replicas: 2
  template:
    metadata:
      labels:
        role: bungee
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                  - key: role
                    operator: In
                    values:
                    - bungee
      containers:
        - name: bungee
          image: gcr.io/stratus-181519/minecraft:bungee-master
          imagePullPolicy: Always
          ports:
            - containerPort: 25570
              name: mc
          envFrom:
            - configMapRef:
                name: bungee-config
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 2Gi
