apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      log
      errors
      health
      kubernetes cluster.local 10.96.0.0/12 {
         pods insecure
         endpoint_pod_names
         upstream /etc/resolv.conf
      }
      prometheus :9153
      proxy . 1.1.1.1:53 1.0.0.1:53
      cache 30 {
        prefetch 10 1m 25%
      }
    }
