apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mixed
spec:
  serviceName: mixed
  selector:
    matchLabels:
      role: mixed
  template:
    metadata:
      labels:
        role: mixed
    spec:
      nodeSelector:
        mixed: 'true'
      containers:
        - name: mixed
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 3000m
              memory: 4Gi
          envFrom:
            - configMapRef:
                name: mixed-config
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
            - name: rotations
              mountPath: /minecraft/rotations:ro
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps
        - name: rotations
          hostPath:
            path: /storage/rotations
