apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbit-secret
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
  RABBITMQ_ERLANG_COOKIE: stratus
  RABBITMQ_NODENAME: rabbit@rabbit-0
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    role: rabbit
spec:
  clusterIP: None
  ports:
    - port: 5672
      name: amqp
    - port: 4369
      name: epmd
    - port: 25672
      name: dist
  selector:
    role: rabbit
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit
spec:
  serviceName: rabbit
  selector:
    matchLabels:
      role: rabbit
  template:
    metadata:
      labels:
        role: rabbit
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: 'true'
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.6-management-alpine
          envFrom:
            - secretRef:
                name: rabbit-secret
          ports:
            - name: queue
              containerPort: 5672
            - name: management
              containerPort: 15672
            - name: cluster
              containerPort: 4369
            - name: dist
              containerPort: 25672
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - rabbitmqctl
                - status
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: volume
              mountPath: /var/lib/rabbitmq:rw
      volumes:
        - name: volume
          emptyDir:
