apiVersion: v1
kind: Service
metadata:
  name: private
  labels:
    role: private
spec:
  clusterIP: None
  ports:
    - port: 25565
      name: minecraft
    - port: 25555
      name: request
  selector:
    role: private
