apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: private
spec:
  serviceName: private
  replicas: 6
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      role: private
  template:
    metadata:
      labels:
        role: private
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: minecraft
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            exec:
              command:
                - ./health.sh
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            exec:
              command:
                - ./health.sh
          resources:
            requests:
              cpu: 950m
              memory: 1.85Gi 
            limits:
              cpu: 950m
              memory: 1.85Gi
          envFrom:
            - configMapRef:
                name: private-pro-config
            - configMapRef:
                name: private-config
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:rw
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps-private-pro
