apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
data:
  STAGE: PRODUCTION
  API: http://api.stratus.network:31113
  RABBIT: rabbit.stratus.network
  BUYCRAFT_SECRET: a13a52df72ac4e570089902994387b6019cbbe10
