apiVersion: v1
kind: Service
metadata:
  name: mapdev
  labels:
    role: mapdev
spec:
  clusterIP: None
  ports:
    - port: 25565
      name: minecraft
  selector:
    role: mapdev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dropbox
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapdev
spec:
  serviceName: mapdev
  selector:
    matchLabels:
      role: mapdev
  template:
    metadata:
      labels:
        role: mapdev
    spec:
      containers:
        - name: minecraft
          image: gcr.io/stratus-197318/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - ready?
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - alive?
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
          envFrom:
            - secretRef:
                name: minecraft-secret
          volumeMounts:
            - name: dropbox
              mountPath: /minecraft/maps:rw
        - name: dropbox
          image: gcr.io/stratus-197318/dropbox:master
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dropbox-secret
          env:
            - name: DROPBOX_FOLDER_REMOTE
              value: /mapdev
            - name: DROPBOX_FOLDER_LOCAL
              value: /minecraft/maps
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: dropbox
              mountPath: /minecraft/maps:rw
      volumes:
        - name: dropbox
          persistentVolumeClaim:
            claimName: dropbox
