apiVersion: v1
kind: Service
metadata:
  name: uhc
  labels:
    role: uhc
spec:
  clusterIP: None
  ports:
    - port: 25565
      name: minecraft
  selector:
    role: uhc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uhc
spec:
  serviceName: uhc
  selector:
    matchLabels:
      role: uhc
  template:
    metadata:
      labels:
        role: uhc
    spec:
      containers:
        - name: minecraft
          image: gcr.io/stratus-197318/minecraft:bukkit-staging
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            exec:
              command:
                - ruby
                - run.rb
                - ready?
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
          envFrom:
            - secretRef:
                name: minecraft-secret
          volumeMounts:
            - name: git
              subPath: maps-staging
              mountPath: /minecraft/maps:ro
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: git
