apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: tm
  labels:
    role: bungee
spec:
  type: NodePort
  ports:
    - port: 25567
      nodePort: 25567
      name: minecraft
  selector:
    role: bungee
