apiVersion: v1
kind: Service
metadata:
  name: bungee
  namespace: tm
  labels:
    role: bungee
spec:
  type: NodePort
  ports:
    - targetPort: 25565
      nodePort: 25576
      port: 25576
      name: minecraft
  selector:
    role: bungee
