apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restart
spec:
  schedule: '0 0 * * *'
  startingDeadlineSeconds: 120
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: restart  
    spec:
      template:
        metadata:
          labels:
            role: restart
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          nodeSelector:
            node-role.kubernetes.io/master: ''
          containers:
            - name: web
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - deployment
                - web
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
            - name: avatar
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - deployment
                - avatar
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
            - name: api
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - deployment
                - api
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
            - name: worker
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - deployment
                - worker
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
          volumes:
            - name: kube
              hostPath:
                path: /root/.kube
