apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  minReadySeconds: 30
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: 'true'
    spec:
      nodeSelector:
        backend: 'true'
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  role: mongo
      containers:
        - name: site
          image: gcr.io/stratus-181519/web:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 30
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 120
            timeoutSeconds: 60
            periodSeconds: 60
            httpGet:
              path: /
              port: 80
          envFrom:
            - secretRef:
                name: web-secret
            - configMapRef:
                name: web-config
          env:
            - name: WEB_ROLE
              value: octc
          volumeMounts:
            - name: data
              mountPath: /minecraft/repo/data:ro
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
        - name: smtp
          image: gcr.io/stratus-181519/smtp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25
              name: smtp
          envFrom:
            - secretRef:
                name: web-secret
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
        - name: data
          image: stratusnetwork/git
          env:
            - name: GIT_CMD
              value: curl http://stratus.network/load_models
            - name: GIT_URL
              value: https://github.com/StratusNetwork/Data.git
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir:
