apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: worker
spec:
  schedule: '0 11 * * *' # 3am pst
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: worker  
    spec:
      template:
        metadata:
          labels:
            role: worker
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          nodeSelector:
            node-role.kubernetes.io/master: ''
          containers:
            - name: worker
              image: stratusnetwork/kubectl:latest
              args:
                - patch
                - deployment
                - worker
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
              volumeMounts:
                - name: kube
                  mountPath: /config/.kube
          volumes:
            - name: kube
              hostPath:
                path: /root/.kube
