apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: worker
spec:
  schedule: '0 */3 * * *' # every 3 hours
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        role: worker
    spec:
      template:
        metadata:
          labels:
            role: worker
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          restartPolicy: Never
          serviceAccountName: system
          containers:
            - name: kubectl
              image: lachlanevenson/k8s-kubectl:latest
              args:
                - patch
                - deployment
                - worker
                - -p
                - "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"restart\":\"$(HOSTNAME)\"}}}}}"
