steps:
  - id: pull
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - gcr.io/$PROJECT_ID/web:master
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/web:$BRANCH_NAME
      - --cache-from=gcr.io/$PROJECT_ID/web:$BRANCH_NAME
      - --build-arg=BRANCH=$BRANCH_NAME
      - web
    wait_for:
      - pull
  - id: tag
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - gcr.io/$PROJECT_ID/web:master
      - gcr.io/$PROJECT_ID/web:latest
    wait_for:
      - build
images:
  - gcr.io/$PROJECT_ID/web:$BRANCH_NAME
  - gcr.io/$PROJECT_ID/web:latest
